# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:nwGo+0ZlQs1RJOtlGsx7k9XMSstrU97aOoLLuTMlAf7ngUuk,iv:5skfh9EvEzcVbZ4GmBH7Xr9lLiVQOlfZgbjY9CxrEAg=,tag:qqdEuedAJg8ZCXAanDOnpA==,type:str]
  credentials.json: ENC[AES256_GCM,data:g11x3NoVhcTNMHRVfn881mt9BB3YCIEIf4ByfgmfYNgf/se9yfVE7sFkxWh74rp4K5BN1FwNVplEtPMW2aKxSr2T0B1cbuGjBnf4ggNloIP7fuwnCwEnIR52CjZGcgkNFgcOENrUFZvemwdxoAfsm5YjQWe2/ve45IkdXQSGd3HOQhF2jeIsAYdIjrJJQzbSWbTCfgBQzSEKJz5jCtr9fh3TStdo/taT9nOyQaud+A==,iv:VPeUHfXeAoKIauBdfVjnKXVtCq3CCKkwgZuT3llpqas=,tag:z5AwnwFtZbRcIbQTQ3ZilQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nf0rucpajc8hg7rsynt9e45r9eexyxcgxgcfamw3dh0gw98mre3qvww64a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WU9yUjFxemFyQ0hYN1pR
        SFVDblpPSU84Y2UzcWRCL0c4aHIxVzdLVEMwClBTQys4TmhpQ3hiaEZwUlRTQmhF
        WUZQbGMxQUxhclNlZGpCV25YUXZBOVUKLS0tIDVsc2ZQbm5KME1NQnBqeWlzS3pZ
        Q2hnNFVXQlJmODJCS1hNV0dBVUJITFUKKn/uHzDu4y4O0huwNUNaezDzH2KvWDrb
        htGs/v24Sjl9zeM47RD2zpj0QlL92wE7tfCQ08Ae/BYYngbOEk4t8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-26T18:33:18Z"
  mac: ENC[AES256_GCM,data:WKh30rT7vaVFCY0XhH6YrppQDP49ydP79ZcuyxSLFOaCBz8XF2601c+s2PcD4ZifcvwiSdMLMzeSINkGBm2d6SNe1amCX6IUZgf19vf0EvWZ7AD2uNy4fF5e4anL/wYcmRWPA/f8b1bQN4e5lXAwplhCZIo45srKLf5V1mA1Gjw=,iv:xkRS1aPkAMU8tTLvBAa5dHrUlab+TUwvofs4K4p/3PQ=,tag:3wL08hmfW0EHc4lE3jz9eQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
