# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:2zLjbM6i/I7kUpsdZl+T+Rxui54J/6/q+TSJ4aUTpO7kir1Z,iv:hf6nT2KfOhYZKSyoP2Bi6fq4+s65LYIJWJ6m4IPfLis=,tag:Ux72IpqbXA/PRCFktZBEpw==,type:str]
  credentials.json: ENC[AES256_GCM,data:CWNKUOYwRuCb7n3GRvtBsUKaEf+iiVU3jlJ0ewIlE/f7HXTI7u8QE7IkCDj1BEhQ8a6Wc6dkJkIXWhxblupP/U94S9XKryDxwW6S8BwiJFFFNwUuDXqdkB+EJOKzNh8FGKx+NevVxY3t0PCD+YgZNOIxNnG1G+zNs8DVubJ2HIHbRazEzOJswOkIAJsbSC6TRVBa1yRL0rBfUTK4t9xilBcA3bO0rLoZ1ne/GNZp5Q==,iv:DMGI8Z/dgM5N9Evue4bJ1Han90hv7mL/fF1qpOymMng=,tag:tdxeRNiPoSKK3FCtbEZ7Fw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nf0rucpajc8hg7rsynt9e45r9eexyxcgxgcfamw3dh0gw98mre3qvww64a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWGpDV1hObzBITWNXSHVy
        Z1pCd2NiRDV4SjRTdWFsdDhrcFRLQlRGZG04CnJUVm44aVJsVWVZYWZxaFU0WGdG
        bjZuUnFiQisxdTZQLzk4MFlXc0dEbkUKLS0tIEFwTUlpN1ZBeE9nRW9FYy9VT3NY
        OGFJWGdNRmpqVjBSVXY1YVYxNy9wVmsKeeq03ou3JlhUoDbX1iUiixd+E0k72W5Z
        f+zJZyY6R3xoGPQdL2NZC5VLzlzrU31QrDxXdO5703SJhbqs+sbXcg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-27T00:36:23Z"
  mac: ENC[AES256_GCM,data:wfoH7ICdLL0/e9uW3ciyQyN6BNODNzU0Uk/xa9a6IjoHGth3cHQn2qifRJZmZ0nMV+MEAB0iFKw2zC00Axh03ChdJX6blIdzahST8FNxq17gjBqh0TxbLi5bb0l1F6YbB2uOTNzUJbTPhJPaSXWgPicpsOO00hbDxJjgm1S0w8k=,iv:exMp4Uw7fGorGhixH1+nZoHgYigOeU7hfaSRyzn/sMA=,tag:LCn++udvi/MjwNZB/hbJ9A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
