# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:cT3Xn46iG2E0/ZXRjoNSk/C3+Ppc9rQ429oIk2sMbBk=,iv:BH2gT4L6somoyUaDOxcWeRn/AsEZruAmW78zzVQGJm4=,tag:i5t4bBGbrd8RQaidbGNBvA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nf0rucpajc8hg7rsynt9e45r9eexyxcgxgcfamw3dh0gw98mre3qvww64a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WldWKzExaVY5U3dnRlFq
        RXVib0NDOW1ZL1RnbXpjODBraDkwQ0RXSGxVCitQSjUyR0ZVcFRPNUN2SWdWTXcy
        SFlheFpRaTJVWHk0WGdYVjJtdCtFNTgKLS0tIEZ3YUphaEFHOTRLdm1VOEhGMVg0
        SEFHaTNGdGxUUVJoVEgxZDFzc1RlRDgKB6p/kLA2vtc2gNZCzems0hU2kBHPXxH1
        O9XH1rm4LGv78+y+VZyfgZBOcUlSFY+vZ18AyY5x08q3kqKkAUcAbw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-26T18:33:18Z"
  mac: ENC[AES256_GCM,data:fq6l3qSjrhhl4hfhDzIdVKohqXRbK8RVdnP4lxXKFpazv3eE2kb3WX4adHsbCDMjy2Zn7Cu3t4rq5jA9OZ0Gidczw5ADPHLih8gckazQ5fzyn1DpqkIokxDbUug5Wu1+vK/GPrCpp0kvWB/I9N+2VqQBqNiQPbwwAaG3ziWCMus=,iv:caFJtB8/5c+1TaHDa6UZ5TuCzhmdnUwagpAsyfKXELk=,tag:vfnT1llGUWWljezL1ptXPQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
