# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:sCjmyNbOSm/kcWqek1ooDNItc/NG33XX8NxBuee0XbdjflLYIQ0/0w==,iv:g8VgctrMQuUat9Ix7zOBN2VsBEANRzMcGLVU/MdY+mY=,tag:Xqc+DCiWPn9NXF3VJGPOwQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nf0rucpajc8hg7rsynt9e45r9eexyxcgxgcfamw3dh0gw98mre3qvww64a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvS3NiUHlVN3pUL3NabmM1
        MmtnNFJDQjJrYjRJWVJGWFJwQ2xyMG9zU2tRCmdVODYxWmpFRWlMQkFCT1JuY3V4
        K2drKzY5RHVDbTJsUDlzY2NEc3dFY0kKLS0tIGZiRnM4TkFNTjBMamRQd3pZQTB3
        aC9DNE1udXZ4RTlySWRNNlZxNHJKN2sKRDOnoYDyZoiMwRONFYZQw9wNA1Swpa0l
        0anfN4FVFVHxzHhZGZfQBGnorXBCi6pvdD+VhI8V9Ol8+JzQcP/bTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-27T00:36:23Z"
  mac: ENC[AES256_GCM,data:pdXAZr/Yms7B4frAQ6831faGwSvjCIC/D4O7bdlkpEoapbbyPZ6MDEWLqyH9b9+huq1/ba+TJbCaatSd6pQBq8y1Bk6Pzh8aQO2oE6mmrZg+Ay9HKNii+3J/zyRKIRMCFbUehZ2voMcehOYR1y52seG3EnDLSSRLFy4b83ZtKLM=,iv:BSNuOmVQzD156udkUsEFDPAlCn2nHoCLeewsJpMPxD0=,tag:EU26jzkmaKBD9SNUwnbyzg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
