# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:gyZzODTsPd8lnA0AIxHd+Tn0lyLRB1jQOLv9jQ1x75xJEsYOHYnzLQ==,iv:GiyeXTyn3zY0nJwP9cdPUGH+5smLk6koZppI4az0rVE=,tag:efUJ3J+emq+IHuo4f4pckg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nf0rucpajc8hg7rsynt9e45r9eexyxcgxgcfamw3dh0gw98mre3qvww64a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbE96SGRCVEJLdmYwdWlt
        a0lnam5mSjNpc2UxN243UmVoZW4welNoTmxRClI2QW91WXRXYUNsdUk2T1B4R0lP
        UXN5OGlacXkvdWwxM1QzQmZ4dzFnUjQKLS0tIGp0YllLRVpMRGlOVWFQUkRvemFp
        TE0rdmZkejVxNFlrVHBSWW5NQ1psN1EK/9bV4Qn0aVF3cJ1dN7aLOZKrahPfqhyM
        aTIsm2bTBYU3jllGZzRB40rxYroUq8cTpfMdyWZpGhAksJggZ2bHLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-27T00:36:23Z"
  mac: ENC[AES256_GCM,data:6AOcGntx+7yYAA47SaD1H15B2U+hZNiTpbZnRRMQs/6x/53Vi33umo8U0bM8AiEP55WUciWXP/QLSjOdtRK4xzUhsOeqEZ/TYjZVDufeKxgEw8+WaXdj09BuPHStp/c2lJEyilqoRHoyRVvbHsa80ZTg90AtZYrxlYz+nXMkJkI=,iv:2lMcbUCtiUH7gS189s8MFbOH68B8Z5HugUKpt6TiQF0=,tag:tfTMq6mQzPEXxj7nr7VesQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
